# A list of subreddits to not bother searching in/bothering/banned from

ignore_list = ["anime", "asianamerican", "askhistorians", "askscience", "aww", "chicagosuburbs", 
    	"cosplay", "cumberbitches", "d3gf", "deer", "depression", "depthhub", 
    	"drinkingdollars", "forwardsfromgrandma", "geckos", "giraffes", 
    	"grindsmygears", "misc", "mixedbreeds", "news", "newtotf2", "omaha", "petstacking", 
    	"pigs", "politicaldiscussion", "politics", "programmingcirclejerk", "raerthdev", 
    	"rants", "runningcirclejerk", "salvia", "science", "seiko", "shoplifting", 
    	"sketches","suicidewatch", "talesfromtechsupport","torrent","torrents","trackers",
	    "tr4shbros", "unitedkingdom", "askreddit", "benfrick", "futurology", 
    	"graphic_design", "historicalwhatif", "lolgrindr", "malifaux", "nfl", 
    	"toonami", "ps2ceres","duelingcorner", "gadgets", "personalfinance", "woahdude",
        "wheredidthesodago", "gentlemanboners", "cats", "business", "holdmybeer", "beer",
        "pcgaming", "motorcycles", "xboxone", "mma", "productivity", "parenting", "horror"
        "enhancement", "biology", "apphookup", "sanfrancisco", "singularity", "transhuman",
        "trucks", "evangelion", "listentous", "multihub", "woahpoon", "careerguidance", "ebola",
        "keming", "aliens", "horses", "internationalpolitics", "libraries", "amazon", "harley",
        "graphicnovels", "dualsport", "milwaukee", "blackops3", "soundsvintage", "fullmoviesonline",
        "calamariraceteam", "listentoobscure", "blackberry", "supermoto", "european", "diesel",
        "batesmotel", "modeltrains", "bikebuilders", "dailyherald", "shittydiy", "askmeanything",
        "troutfishing", "hackedgadgets", "musicguides", "fayetteville", "englishlearning",
        "mentalfloss", "deathrowdiesel", "listentocurated", "southbend", "subredditreports",
        "gasmonkey", "bitcoinbeg", "listentousagain", "listentonew", "420", "gwar", "weaponsystems",
        "rants", "tforcenetwork", "summit", "breckenridge", "hogfornoobs", "artreddits", "tcgcollecting",
        "battletops", "sliders", "caddenmorandiary", "radd_it", "decaf", "woahgifs", "radditplaylists", 
        "subofrome", "rainbow", "botwatchman", "fuckharley", "etfs", "neogaf", "svara", "msawareness", 
        "metrosexual", "replygore", "usfreepress", "critterart", "3dchalk", "futurologymoderators", 
        "truckmemes", "cssstyle", "happynews", "biochemistry2", "parables", "osiris", "truedisability", 
        "futurologyappeals", "radditfaq", "weedtrees", "trglodyte", "happyworldnews", "stevediary",
        "blacklistpics", "serendipity", "pcmasterrace", "minecraft", "photoshopbattles", "interestingasfuck",
        "peoplebeingjerks", "animalsbeingjerks", "gaming", "awwnime", "k_on", "blackfellas",
        "games", "dvdcollection", "animefigures", "modernmagic", "australia", "calligraphy",
        "blackladies", "firefighting", "womenwithwatches", "kotakuinaction", "mechanicalkeyboards",
        "android", "wtf", "cringe", "dbz", "skeptic", "knives", "pics", "pic", "unexpected", "adviceanimals",
        "twoxchromosomes", "lewronggeneration", "nascar", "badphilosophy", "gifs",
        "philosophy", "censorship", "conservative", "fatlogic", "historyofideas", "earthprobes",
        "fantasyfootball", "redditarmie", "mistyfront", "reclaimedbynature", "blackpeopletwitter", "gamephysics",
        "programmerhumor", "technology", "worldnews", "youtubehaiku", "movies", "shittyprogramming", "sports",
        "music", "books", "history", "food", "television", "art", "diy", "warhammer", "flicks", "moescape", "asatru",
        "cringepics", "getmotivated", "conspiratard", "mindcrack", "soccer", "troy", "femradebates", "pussypassdenied",
        "lotr", "delaware", "foreveralone", "trollxchromosomes", "netsec", "tiara", "horror", "funny", "gif",
        "nationalpark", "celebs", "prettygirls", "surpriseddogs", "bellathorne", "delawarepolitics",
        "gunsarecool", "stardustcrusaders", "creepypms", "bears", "space", "denmark", "ireland", "damnthatsinteresting",
        "thriftstorehauls", "metalgearsolidv_pc", "etimusic", "rage", "osha", "zettairyouiki", "gameofthrones", "sinotibetan",
        "hopheadsde", "thailand", "romania", "photoshopfail", "cynicalbrit", "serverporn", "whatcouldgowrong",
        "kanmusu", "hardware", "sociology", "conspiracy", "perfecttiming", "largeimages", "republican", "dnb",
        "eatcheapandhealthy", "food", "foodporn", "agarioball", "codzombies", "listentothis", "europe", "bouldering",
        "euromusic", "barca", "destinythegame", "polandball", "stateball", "planetball", "polandballart", "panda",
        "fpvracing", "denvernuggets", "freethought", "aquariums", "vive", "specart", "animation", "comics",
        "steroids", "arkansas", "slammedtrucks", "oc_cars", "happygifs", "nba", "pizza", "abcdesis", "linguistics",
        "photography", "syriancivilwar", "progolf", "altbriggs", "headpats", "beautifulfemales", "bakchodi",
        "wec", "blancpain", "consoleproletariat", "blackandgold", "imaginarymonsters", "imaginarylandscapes",
        "imaginarycharacters", "adorableart", "bengals", "soma", "frontpage", "whatisthis", "lawschool",
        "shitamericanssay", "cbc_radio", "colorado", "redditdads", "apotheoun", "hyomin", "newzealand", "publicfreakout",
        "beachdogs", "catholicism", "chemistry", "montreal", "longbeards", "fishing", "slowcooking", "everythingscience",
        "retrobattlestations", "electricians", "crossdressing", "starwars", "iamverysmart", "cowboys", "userexperience",
        "japanesewatches", "opiates", "2007scape", "korean", "gamedeals", "blind", "blackpeoplegifs", "animalsbeingbros",
        "analogygifs", "camping", "cityporn", "bestofreports", "memes", "internetisbeautiful", "highqualitygifs",
        "humansbeingbros", "rage", "reactiongifs", "hifw", "nottheonion", "reversegif", "thingsthatblowup", "youdontsurf",
        "wastedgifs", "genderqueer", "imagesofnewyork", "imagesofcanada", "imagesofusa", "imagesofalabama", "miiverseinaction",
        "tattoos", "seahawks", "conspiracymemes", "justneckbeardthings", "ar15", "trance", "5555555", "commentsgetdrawn",
        "unitedstatesofamerica", "workbenches", "philippines", "tng", "leagueofmemes", "atari", "kiddet", "hillaryclinton",
        "boston", "coffee", "weekendgunnit", "cardinals", "torontobluejays", "military", "goldreplies", "shinjimin",
        "losangeleskings", "writermotivation", "kerbalplanes", "sto", "latino", "southflorida", "mylittleandysonic1", "zika",
        "babyrooms", "nononono", "overlanding", "ak47", "callofduty", "bbcradiodrama", "the_crew", "shittydarksouls", "atheism",
        "badtattoos", "army", "quityourbullshit", "mycology", "brokengifs", "catslaps", "albany", "canadaguns", "makeupaddiction",
        "freeeuropenews", "naruto", "magnificentmemes"]
