list = ["anime", "asianamerican", "askhistorians", "askscience", "aww", "chicagosuburbs", 
    	"cosplay", "cumberbitches", "d3gf", "deer", "depression", "depthhub", 
    	"drinkingdollars", "forwardsfromgrandma", "geckos", "giraffes", 
    	"grindsmygears", "misc", "mixedbreeds", "news", "newtotf2", "omaha", "petstacking", 
    	"pigs", "politicaldiscussion", "politics", "programmingcirclejerk", "raerthdev", 
    	"rants", "runningcirclejerk", "salvia", "science", "seiko", "shoplifting", 
    	"sketches","suicidewatch", "talesfromtechsupport","torrent","torrents","trackers",
	    "tr4shbros", "unitedkingdom", "askreddit", "benfrick", "futurology", 
    	"graphic_design", "historicalwhatif", "lolgrindr", "malifaux", "nfl", 
    	"toonami", "ps2ceres","duelingcorner", "gadgets", "personalfinance", "woahdude",
        "wheredidthesodago", "gentlemanboners", "cats", "business", "holdmybeer", "beer",
        "pcgaming", "motorcycles", "xboxone", "mma", "productivity", "parenting", "horror"
        "enhancement", "biology", "apphookup", "sanfrancisco", "singularity", "transhuman",
        "trucks", "evangelion", "listentous", "multihub", "woahpoon", "careerguidance", "ebola"
        "keming", "aliens", "horses", "internationalpolitics", "libraries", "amazon", "harley",
        "graphicnovels", "dualsport", "milwaukee", "blackops3", "soundsvintage", "fullmoviesonline",
        "calamariraceteam", "listentoobscure", "blackberry", "supermoto", "european", "diesel",
        "batesmotel", "modeltrains", "bikebuilders", "dailyherald", "shittydiy", "askmeanything",
        "troutfishing", "hackedgadgets", "musicguides", "fayetteville", "englishlearning",
        "mentalfloss", "deathrowdiesel", "listentocurated", "southbend", "subredditreports",
        "gasmonkey", "bitcoinbeg", "listentousagain", "listentonew", "420", "gwar", "weaponsystems",
        "rants", "tforcenetwork", "summit", "breckenridge", "hogfornoobs", "artreddits", "tcgcollecting",
        "battletops", "sliders", "caddenmorandiary", "radd_it", "decaf", "woahgifs", "radditplaylists", 
        "subofrome", "rainbow", "botwatchman", "fuckharley", "etfs", "neogaf", "svara", "msawareness", 
        "metrosexual", "replygore", "usfreepress", "critterart", "3dchalk", "futurologymoderators", 
        "truckmemes", "cssstyle", "happynews", "biochemistry2", "parables", "osiris", "truedisability", 
        "futurologyappeals", "radditfaq", "weedtrees", "trglodyte", "happyworldnews", "stevediary",
        "blacklistpics", "serendipity", "pcmasterrace", "minecraft", "photoshopbattles", "interestingasfuck",
        "peoplebeingjerks", "animalsbeingjerks", "gaming", "awwnime", "k_on", "blackfellas",
        "games", "dvdcollection", "animefigures", "modernmagic", "australia", "calligraphy",
        "blackladies", "firefighting", "womenwithwatches", "kotakuinaction", "mechanicalkeyboards",
        "android", "wtf", "cringe", "dbz", "skeptic", "knives", "pics", "pic", "unexpected", "adviceanimals",
        "twoxchromosomes", "lewronggeneration", "nascar", "badphilosophy", "gifs",
        "philosophy", "censorship", "conservative", "fatlogic", "historyofideas", "earthprobes",
        "fantasyfootball", "redditarmie", "mistyfront", "reclaimedbynature", "blackpeopletwitter", "gamephysics",
        "programmerhumor", "technology", "worldnews", "youtubehaiku", "movies", "shittyprogramming", "sports",
        "music", "books", "history", "food", "television", "art", "diy"]