list = ["anime", "asianamerican", "askhistorians", "askscience", "aww", "chicagosuburbs", 
    	"cosplay", "cumberbitches", "d3gf", "deer", "depression", "depthhub", 
    	"drinkingdollars", "forwardsfromgrandma", "geckos", "giraffes", 
    	"grindsmygears", "misc", "mixedbreeds", "news", "newtotf2", "omaha", "petstacking", 
    	"pigs", "politicaldiscussion", "politics", "programmingcirclejerk", "raerthdev", 
    	"rants", "runningcirclejerk", "salvia", "science", "seiko", "shoplifting", 
    	"sketches","suicidewatch", "talesfromtechsupport","torrent","torrents","trackers",
	    "tr4shbros", "unitedkingdom", "askreddit", "benfrick", "futurology", 
    	"graphic_design", "historicalwhatif", "lolgrindr", "malifaux", "nfl", 
    	"toonami", "ps2ceres","duelingcorner"]